config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #pages
  get "/", to: "pages#home", as:"root"

  #Show all listings
  get "/listings", to: "listings#index", as: "listings"
  #create listing
  get "/listings/new", to: "listings#new", as: "new_listing"
  #show listing
  get "/listings/:id", to: "listings#show", as: "listing"
  #edit listing
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  #create listing
  post "/listings", to: "listings#create", as: "create_listing"
  #update listing
  patch "/listings/:id", to: "listings#update", as: "update_listing"
  #delete listing
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"

  #new rooms
  get "/rooms/new/:list_id", to: "rooms#new", as: "new_room"
  #create room
  post "/rooms/:list_id", to: "rooms#create", as: "create_room"
  #show room
  get "/rooms/:id", to: "rooms#show", as: "room"
  #edit room
  get "/rooms/:id/edit", to: "rooms#edit", as: "edit_room"
  #update room
  patch "/rooms/:id", to: "rooms#update", as: "update_room"
  #delete room
  delete "/rooms/:id", to: "rooms#destroy", as: "delete_room"

  #bookings
  get "/bookings", to: "bookings#index", as: "bookings"  

  #profile
  get "/profiles", to: "profiles#index", as: "profiles"
  #new profile
  get "/profiles/new", to: "profiles#new", as:"new_profile"
  #view profile
  get "/profiles/:id", to: "profiles#show", as: "profile"
  #edit profile
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  #update profile
  patch "/profiles/:id", to: "profiles#update", as: "update_profile"
  #create profile
  post "/profiles", to: "profiles#create", as:"create_profile"

  get "/pages/payment/:room_id", to: "pages#payment", as: "payment"
  get "/pages/pay_confirm/:room_id/:date_from/:date_to", to: "pages#pay_confirm", as: "pay_confirm"
  
  get "/payments", to: "payments#index", as: "payments"

  get "/addresses", to: "addresses#index", as: "addresses"

end

app/models/listing.rb
class Listing < ApplicationRecord
    has_many :rooms, dependent: :destroy
    belongs_to :user
    accepts_nested_attributes_for :rooms
    
    has_one_attached :picture
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    load_and_authorize_resource
    before_action :set_search
    before_action :print_params
    before_action :set_listing, only: [:show, :edit, :update, :destroy]

    def print_params
        p "***********"
        p params
        p "***********"
    end

    def new
        @listing = Listing.new()        #create new listing entry
    end

    def create
        #create the listing
        @listing = Listing.create(listing_params)
        @listing.update(user_id: current_user[:id])     #update user id
        
        redirect_to listings_path       #redirect to listing
    end

    def index
        session[:search] = {}           #clear search cookie
    
        if params[:search] != nil   #if a search
            #check params
            if (params[:search][:location] != '' && params[:search][:no_people] != '' &&
            params[:search][:date_from] != '' && params[:search][:date_to] != '')
                #check if the dates are valid
                if (Date.parse(params[:search][:date_to]) - Date.parse(params[:search][:date_from])) >= 1
                    session[:search] = search_params                                                        #save search params to cookies
                    @listings = Listing.where(location: params[:search][:location].downcase.capitalize)     #set listings that match location
                else
                    p 'wrong dates'
                    redirect_to root_path           #if date invalid, redirect to home
                end
            else
                p 'incomplete search'
                redirect_to root_path               #if not all search input filled in, redirect to home
            end
        else
            #if not search, list all listing for current user (seller)
            @listings = Listing.where(user_id: current_user.id)
        end
    end 

    def show
        @search = session[:search]          #set search from cookies
        p "cookie - search"
        pp @search
        p @search['no_people']
        
        @booking_text = ""                  #clear booking text

        if @search != {}                    #if a search
            #set rooms that match conditions
            @rooms_list = Room.where("listing_id = ? AND no_people = ?", params[:id], @search["no_people"].to_i)
            @rooms = []
            @rooms_list.each{|r|
                #push to @rooms if avaliable on all dates in query
                if date_aval(r,@search["date_from"],@search["date_to"])
                    @rooms.push(r)
                    p "pushed #{r}"
                end
            }
            @booking_text = "Book for #{@search["date_from"]} - #{@search["date_to"]}" #set booking text
        else
            @rooms = Room.where(listing_id: params[:id])        #if not search, set to all rooms of listing
        end
    end

    
    
    def edit
        @rooms = Room.where(listing_id: params[:id])            #set rooms of current listing
    end
    
    def update
        #update listing
        @listing.update(name: params[:listing][:name])       
        @listing.update(location: params[:listing][:location])
        redirect_to listings_path                               #redirect to listing
    end



    def destroy
        @listing.destroy                    #delete listing
        redirect_to listings_path           #redirect to listing index
    end

    def date_aval(room, date_from, date_to)                 #check if avaliable between dates
        for i in 1..room.bookings.length                    #for all booking in room
            booking_temp = room.bookings.find_by(date: date_from)   #set booking_temp to booking on date_from
            p booking_temp
            if booking_temp[:aval]                          #check if booking avaliable on date  
                if date_from == date_to                     #if date_from is equal to date_to
                    return true                             #return true (avaliable between dates)
                else
                    date_from = (Date.parse(date_from) + 1).to_s        #increment date_from if not matching
                end
            else
                return false                    #if booking not avaliable
            end
        end

    end

    private
    def set_listing
        #set listing by id
        id = params[:id]
        @listing = Listing.find(id)
    end

    def listing_params
        #permit listing params
        params.require(:listing).permit(:name,:location,:picture)
    end

    def room_params
        #permit room params
        params.require(:room).permit(:name,:price,:no_people)
    end

    def search_params
        #permit search params
        params.require(:search).permit(:location, :no_people, :date_from, :date_to)
    end

    def set_search
        @search = session[:search]
        p "----]]]]----"
        pp @search
    end
end

app/views/listings/edit.html.erb
<div class="page_sec">
    <div class="card mb-3" style="max-width: 800px; width: 60vw">
        <div class="row no-gutters">
            <div class="col-md-3">
            <%= image_tag @listing.picture, :class => "listing_img" if @listing.picture.attached? %>
            </div>
            <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= @listing[:name] %></h5>
                <%= form_with model: @listing do |form| %>
                    <div>
                    <%= form.label :name %>
                    <%= form.text_field :name %>
                    </div>
                    <div>
                    <%= form.label :location %>
                    <%= form.text_field :location %>
                    </div>
                    <%= form.submit %>
                <% end %>
            </div>
            </div>
        </div>
    </div>

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Adipisci quae porro temporibus qui minima quidem doloremque maxime, tenetur quasi. Et alias eaque maiores autem molestias obcaecati dolor minus, quas repellat.
    Maxime similique, accusamus aliquid necessitatibus totam est praesentium quam vel corporis magnam libero ducimus amet architecto numquam laborum molestiae veritatis, non, iste officia error magni. Nulla nihil atque exercitationem labore!
    Reiciendis, velit unde ducimus, reprehenderit blanditiis saepe similique dolorum vel ipsam quisquam facilis aperiam libero nesciunt, sed laboriosam? Natus doloremque inventore officia consectetur totam repudiandae explicabo, excepturi reprehenderit sed! Rem.
    Totam porro unde deleniti. Natus asperiores pariatur, molestiae neque vel sequi! Ad ea enim ratione nam labore soluta hic quibusdam, pariatur ab, expedita placeat. Accusamus, autem? Culpa a sit reprehenderit.
    Incidunt tempore minima fugiat non provident doloribus laborum, laboriosam vitae sunt quae assumenda atque, earum quos fuga ipsum vel sequi corrupti. Exercitationem consequuntur deserunt deleniti sed placeat nisi sit iusto?</p>


    <%= link_to "Delete Listing", delete_listing_path(@listing[:id]),method: :delete, data: {confirm: "Are you sure?"}%>
</div>

app/views/listings/index.html.erb
<div class="page_sec">
    <% @listings.each{ |list| %>

        <div class="card mb-3" style="max-width: 800px; width: 60vw">
        <div class="row no-gutters">
            <div class="col-md-3"  style="background-color: gray">
            <%= image_tag list.picture, :class => "listing_img" if list.picture.attached? %>
            </div>
            <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= list[:name] %></h5>
                <p><%= list[:location] %></p>
                <%= link_to "View", "/listings/#{list[:id]}" %>
            </div>
            </div>
        </div>
        </div>
    <%}%>
</div>


<% if can? :create, Listing %><%= link_to "New Listing", new_listing_path %><% end %>

app/views/listings/new.html.erb
<div class="page_sec">
    <%= form_with(model: @listing, local: true) do |form| %>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :location %>
            <%= form.text_field :location %>
        </div>
        <div>
            <%= form.label :picture, value="Image" %>
            <%= form.file_field :picture %>
        </div>
        <%= form.submit %>
    <% end %>
</div>

app/views/listings/show.html.erb
<div class="page_sec">
    <div class="card mb-3" style="max-width: 800px; width: 60vw">
        <div class="row no-gutters">
            <div class="col-md-3">
            <%= image_tag @listing.picture, :class => "listing_img" if @listing.picture.attached? %>
            </div>
            <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= @listing[:name] %></h5>
                <p><%= @listing[:location] %></p>
                <p>Id: <%= @listing[:id]%></p>
                <% if can? :update, @listing%><%= link_to "Edit Listing", edit_listing_path(params[:id]) %><% end %>
            </div>
            </div>
        </div>
    </div>

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Adipisci quae porro temporibus qui minima quidem doloremque maxime, tenetur quasi. Et alias eaque maiores autem molestias obcaecati dolor minus, quas repellat.
    Maxime similique, accusamus aliquid necessitatibus totam est praesentium quam vel corporis magnam libero ducimus amet architecto numquam laborum molestiae veritatis, non, iste officia error magni. Nulla nihil atque exercitationem labore!
    Reiciendis, velit unde ducimus, reprehenderit blanditiis saepe similique dolorum vel ipsam quisquam facilis aperiam libero nesciunt, sed laboriosam? Natus doloremque inventore officia consectetur totam repudiandae explicabo, excepturi reprehenderit sed! Rem.
    Totam porro unde deleniti. Natus asperiores pariatur, molestiae neque vel sequi! Ad ea enim ratione nam labore soluta hic quibusdam, pariatur ab, expedita placeat. Accusamus, autem? Culpa a sit reprehenderit.
    Incidunt tempore minima fugiat non provident doloribus laborum, laboriosam vitae sunt quae assumenda atque, earum quos fuga ipsum vel sequi corrupti. Exercitationem consequuntur deserunt deleniti sed placeat nisi sit iusto?</p>

    <% @rooms.each { |r| %>
        <button type="button" class="btn btn-outline-primary"><%= link_to r[:name], room_path(r.id), :class => "room-btn"%> <%= link_to @booking_text, 
        payment_path(r.id,@search["date_from"],@search["date_to"]) %></button>
    <% } %>
        <button type="button" class="btn btn-outline-primary"><% if can? :create, @listing %><%= link_to "New Room", new_room_path(params[:id]) %><% end %></button>
</div>