config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #pages
  get "/", to: "pages#home", as:"root"

  #Show all listings
  get "/listings", to: "listings#index", as: "listings"
  #create listing
  get "/listings/new", to: "listings#new", as: "new_listing"
  #show listing
  get "/listings/:id", to: "listings#show", as: "listing"
  #edit listing
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  #create listing
  post "/listings", to: "listings#create", as: "create_listing"
  #update listing
  patch "/listings/:id", to: "listings#update", as: "update_listing"
  #delete listing
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"

  #new rooms
  get "/rooms/new/:list_id", to: "rooms#new", as: "new_room"
  #create room
  post "/rooms/:list_id", to: "rooms#create", as: "create_room"
  #show room
  get "/rooms/:id", to: "rooms#show", as: "room"
  #edit room
  get "/rooms/:id/edit", to: "rooms#edit", as: "edit_room"
  #update room
  patch "/rooms/:id", to: "rooms#update", as: "update_room"
  #delete room
  delete "/rooms/:id", to: "rooms#destroy", as: "delete_room"

  #bookings
  get "/bookings", to: "bookings#index", as: "bookings"  

  #profile
  get "/profiles", to: "profiles#index", as: "profiles"
  #new profile
  get "/profiles/new", to: "profiles#new", as:"new_profile"
  #view profile
  get "/profiles/:id", to: "profiles#show", as: "profile"
  #edit profile
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  #update profile
  patch "/profiles/:id", to: "profiles#update", as: "update_profile"
  #create profile
  post "/profiles", to: "profiles#create", as:"create_profile"

  get "/pages/payment/:room_id", to: "pages#payment", as: "payment"
  get "/pages/pay_confirm/:room_id/:date_from/:date_to", to: "pages#pay_confirm", as: "pay_confirm"
  
  get "/payments", to: "payments#index", as: "payments"

  get "/addresses", to: "addresses#index", as: "addresses"

end

app/views/shared/_details_form.html.erb
<%= form_with(model: @profile, local: true, class: "profile_form")  do |form| %>
    <div class="personal_field">
        <div class="profile_data">
            <%= form.label :fname, value: "First Name"%>
            <%= form.text_field :fname%>
        </div>
        <div class="profile_data">
            <%= form.label :lname, value: "Surname"%>
            <%= form.text_field :lname%>
        </div>
        <div class="profile_data">
            <%= form.label :phone %>
            <%= form.text_field :phone%>
        </div>
    </div>
    <h3 class="form_title_payment">Payment Details</h3>
    <div class="payment_field">
        
        <%= form.fields_for @payment do |pay_form|%>
            <div class="profile_data">
                <%= pay_form.label :card_no %>
                <%= pay_form.text_field :card_no %>
            </div>
            <div class="profile_data">
                <%= pay_form.label :card_name %>
                <%= pay_form.text_field :card_name %>
            </div>
            <div class="profile_data">
                <%= pay_form.label :CSV %>
                <%= pay_form.text_field :CSV %>
            </div>
            <div class="profile_data">
                <%= pay_form.label :expiry %>
                <%= pay_form.text_field :expiry %>
            </div>
        <% end %>
    </div>
    <h3 class="form_title_address">Address Details</h3>
    <div class="address_field">
        
        <%= form.fields_for @address do |add_form|%>
            
            <div class="profile_data">
                <%= add_form.label :street_no %>
                <%= add_form.text_field :street_no %>
            </div>
            <div class="profile_data">
                <%= add_form.label :street_name %>
                <%= add_form.text_field :street_name %>
            </div>
            <div class="profile_data">
                <%= add_form.label :suburb %>
                <%= add_form.text_field :suburb %>
            </div>
            <div class="profile_data">
                <%= add_form.label :state %>
                <%= add_form.text_field :state %>
            </div>
            <div class="profile_data">
                <%= add_form.label :postcode %>
                <%= add_form.text_field :postcode %>
            </div>
            
        <% end %>
    </div>
    <div>
    <% if can? :edit, User %>
        <%= form.fields_for @user do |user_form|%>
            <%= user_form.label :admin %>
            <%= user_form.select :admin, [["Customer", 1],["Seller", 2],["Admin", 3]]%>
        <% end %>
    <% end %>
    </div>

    <div>
    <%= form.submit %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse_target" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="collapse_target">
      <ul class="navbar-nav mr-auto">
      
        <li class="nav-item">
          <%= link_to "Home", root_path, :class => "nav-link" %>
        </li>

        <li class="nav-item">
          <% if user_signed_in? %><%= link_to "Profile", profiles_path, :class => "nav-link" %><% end %>
        </li>
        
        <li class="nav-item">
          <% if can? :manage, Listing %><%= link_to "Listing", listings_path, :class => "nav-link" %><% end %>
        </li>
        
        <li class="nav-item">
          <% if user_signed_in? %><%= link_to "Bookings", bookings_path, :class => "nav-link" %><% end %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete , :class => "nav-link" %></li>
          <li class="nav-item"><p class="nav-link">Logged In as <%= current_user[:email]%></p></li>
        
        <% else %>
          <li class="nav-item"><%= link_to "Sign In", new_user_session_path, :class => "nav-link" %></li>
          <li class="nav-item"><%= link_to "Register", new_user_registration_path, :class => "nav-link" %></li>
        <% end %>
      </ul>
    </div>
    <div>
      <form action = "<%=listings_path%>" method = "GET" class="search_nav">
        <div>
          <label>Location: </label>
          <input type="text" name="search[location]" class="search_input">
        </div>
        <div>
          <label>People: </label>
          <input type="number" step="1" min="1" max="4" name="search[no_people]" class="search_no_people" class="search_input">
        </div>
        <div>
          <label>From: </label>
          <input type="date" name="search[date_from]" class="search_input">
        </div>
        <div>
          <label>To: </label>
          <input type="date" name="search[date_to]" class="search_input">
        </div>
        <input type="submit" value="Search">
      </form>

    </div>
  </nav>