config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #pages
  get "/", to: "pages#home", as:"root"

  #Show all listings
  get "/listings", to: "listings#index", as: "listings"
  #create listing
  get "/listings/new", to: "listings#new", as: "new_listing"
  #show listing
  get "/listings/:id", to: "listings#show", as: "listing"
  #edit listing
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  #create listing
  post "/listings", to: "listings#create", as: "create_listing"
  #update listing
  patch "/listings/:id", to: "listings#update", as: "update_listing"
  #delete listing
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"

  #new rooms
  get "/rooms/new/:list_id", to: "rooms#new", as: "new_room"
  #create room
  post "/rooms/:list_id", to: "rooms#create", as: "create_room"
  #show room
  get "/rooms/:id", to: "rooms#show", as: "room"
  #edit room
  get "/rooms/:id/edit", to: "rooms#edit", as: "edit_room"
  #update room
  patch "/rooms/:id", to: "rooms#update", as: "update_room"
  #delete room
  delete "/rooms/:id", to: "rooms#destroy", as: "delete_room"

  #bookings
  get "/bookings", to: "bookings#index", as: "bookings"  

  #profile
  get "/profiles", to: "profiles#index", as: "profiles"
  #new profile
  get "/profiles/new", to: "profiles#new", as:"new_profile"
  #view profile
  get "/profiles/:id", to: "profiles#show", as: "profile"
  #edit profile
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  #update profile
  patch "/profiles/:id", to: "profiles#update", as: "update_profile"
  #create profile
  post "/profiles", to: "profiles#create", as:"create_profile"

  get "/pages/payment/:room_id", to: "pages#payment", as: "payment"
  get "/pages/pay_confirm/:room_id/:date_from/:date_to", to: "pages#pay_confirm", as: "pay_confirm"
  
  get "/payments", to: "payments#index", as: "payments"

  get "/addresses", to: "addresses#index", as: "addresses"

end

app/views/pages/home.html.erb
<div class="back_1" style= "background-image: linear-gradient(rgba(0, 100, 100, 0.5), rgba(100, 100, 100, 0.8)), url(<%= asset_path 'home.jpg' %>);">
    <div class="card bg-light mb-3" style="max-width: 25rem">
        <div class="card-body">
            <form action = "<%=listings_path%>" method = "GET" class="search_bar">
                <div class="search_div">
                    <label>Location: </label>
                    <input type="text" name="search[location]" class="search_input">
                </div>
                <div class="search_div">
                    <label>People: </label>
                    <input type="number" step="1" min="1" max="4" name="search[no_people]" class="search_input">
                </div>
                <div class="search_div">
                    <label>From: </label>
                    <input type="date" name="search[date_from]" class="search_input">
                </div>
                <div class="search_div">
                    <label>To: </label>
                    <input type="date" name="search[date_to]" class="search_input">
                </div>
                <input type="submit" value="Search">
            </form>
        </div>
    </div>
</div>

app/views/pages/pay_confirm.html.erb
<div class="page_sec">
    <h1>Payment Confirmed</h1>
    <p>Booking made for Listing: <%= @room.listing[:name]%>  Room: <%= @room[:name]%>  $<%= @room[:price]%> <%= @room[:no_people]%>ppl 
    Total: $<%= @room[:price] * @room[:no_people] * (@date_to.to_date - @date_from.to_date).to_i %> 
    Nights: <%= (@date_to.to_date - @date_from.to_date).to_i %></p>
    <p>Dates: <%= @date_from %> to <%= @date_to %></p>
</div>

app/views/pages/payment.html.erb
<div class="page_sec">
    <div>
        <div class="personal_field">
            <div class="profile_data">First Name: <%= @profile[:fname]%></div>
            <div class="profile_data">Last Name: <%= @profile[:lname]%></div>
            <div class="profile_data">Phone: <%= @profile[:phone]%></div>
        </div>
        <h3 class="form_title_payment">Payment Details</h3>
        <div class="payment_field">
            <div class="profile_data">Card No.: ****<%= @profile.payment[:card_no].to_s.slice(-4,4)%></div>
        </div>
        <h3 class="form_title_address">Address Details</h3>
        <div class="address_field">
            <div class="profile_data">Street No.: <%= @profile.address[:street_no]%></div>
            <div class="profile_data">Street Name: <%= @profile.address[:street_name]%></div>
            <div class="profile_data">Suburb: <%= @profile.address[:suburb]%></div>
            <div class="profile_data">State: <%= @profile.address[:state]%></div>
            <div class="profile_data">Postcode: <%= @profile.address[:postcode]%></div>
        </div>
        <div class="profile_edit_btn">
            <%= link_to "Edit Profile", edit_profile_path(Profile.find_by(user_id: current_user[:id]))%>
        </div>
    </div>


    <p>Room: <%= @room[:name]%>  $<%= @room[:price]%> <%= @room[:no_people]%>ppl 
    Total: $<%= @room[:price] * @room[:no_people] * (@date_to.to_date - @date_from.to_date).to_i %> 
    Nights: <%= (@date_to.to_date - @date_from.to_date).to_i %></p>
    <p>Dates: <%= @date_from %> to <%= @date_to %></p>
    <%= link_to "Confim Booking", pay_confirm_path(@room.id, @date_from, @date_to) %>
</div>