config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #pages
  get "/", to: "pages#home", as:"root"

  #Show all listings
  get "/listings", to: "listings#index", as: "listings"
  #create listing
  get "/listings/new", to: "listings#new", as: "new_listing"
  #show listing
  get "/listings/:id", to: "listings#show", as: "listing"
  #edit listing
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  #create listing
  post "/listings", to: "listings#create", as: "create_listing"
  #update listing
  patch "/listings/:id", to: "listings#update", as: "update_listing"
  #delete listing
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"

  #new rooms
  get "/rooms/new/:list_id", to: "rooms#new", as: "new_room"
  #create room
  post "/rooms/:list_id", to: "rooms#create", as: "create_room"
  #show room
  get "/rooms/:id", to: "rooms#show", as: "room"
  #edit room
  get "/rooms/:id/edit", to: "rooms#edit", as: "edit_room"
  #update room
  patch "/rooms/:id", to: "rooms#update", as: "update_room"
  #delete room
  delete "/rooms/:id", to: "rooms#destroy", as: "delete_room"

  #bookings
  get "/bookings", to: "bookings#index", as: "bookings"  

  #profile
  get "/profiles", to: "profiles#index", as: "profiles"
  #new profile
  get "/profiles/new", to: "profiles#new", as:"new_profile"
  #view profile
  get "/profiles/:id", to: "profiles#show", as: "profile"
  #edit profile
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  #update profile
  patch "/profiles/:id", to: "profiles#update", as: "update_profile"
  #create profile
  post "/profiles", to: "profiles#create", as:"create_profile"

  get "/pages/payment/:room_id", to: "pages#payment", as: "payment"
  get "/pages/pay_confirm/:room_id/:date_from/:date_to", to: "pages#pay_confirm", as: "pay_confirm"
  
  get "/payments", to: "payments#index", as: "payments"

  get "/addresses", to: "addresses#index", as: "addresses"

end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :listing
    has_many :bookings, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    load_and_authorize_resource
    before_action :set_search
    before_action :set_room, only: [:show, :edit, :update, :destroy]
    before_action :set_listing, only: [:new, :create]

    def show
        p params
        @bookings = Booking.where(room_id: params[:id])     #find booking of room
        pp @rooms
    end

    def new

    end
    
    def create
        days_params = params.require(:days_num).to_i        #require only days_num
        
        #create the rooms
        @room = Room.create(listing_id: @listing[:id], aval: true)
        @room.update(room_params)               #update using room_params

        for i in 0..days_params         #for i is 0 to the number of days
            #create bookings
            @booking = Booking.create(date: (Date.parse(params[:booking][:date]) + i), aval: true, room_id: @room[:id])
        end
        
        redirect_to listing_path(@listing[:id])     #redirect to listing
    end
    
    def edit
        @bookings = Booking.where(room_id: params[:id])     #find bookings of room
    end

    def update
        #update room values
        @room.update(name: params[:room][:name])
        @room.update(price: params[:room][:price])
        @room.update(no_people: params[:room][:no_people])
        redirect_to room_path(@room.id)     #redirect to show room
    end

    def destroy
        @room.destroy           #delete room
        redirect_to listings_path       #redirect to listing
    end

    private
    def set_listing
        #set listing from params
        id = params[:list_id]
        @listing = Listing.find(id)
        p '----///---'
        p @listing
    end
    def set_room
        #set room from params
        id = params[:id]
        @room = Room.find(id)
    end

    def room_params
        #permit room values
        params.require(:room).permit(:name,:price,:no_people)
    end

    def set_search
        #save search from cookies
        @search = session[:search]
    end
end

app/views/rooms/edit.html.erb
<div class="page_sec">
    <h3>Room: <%= @room[:name]%></h3>
    <p>Id: <%= @room[:id]%></p>

    <%= form_with(model: @room) { |form|%>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :price %>
            <%= form.text_field :price %>
        </div>
        <div>
            <%= form.label :no_people %>
            <%= form.text_field :no_people %>
        </div>
        <%= form.submit %>
    <% } %>

    <%= link_to "Delete Room", delete_room_path(@room[:id]),method: :delete, data: {confirm: "Are you sure?"}%>

    <%= month_calendar events: @bookings do |date, bookings| %>
        <%= date.day %>
        <% bookings.each do |b| %>
            <% if b[:aval] %>
                <p>Vacant</p>
            <% else %>
                <p>No Vacancy</p>
            <% end %>
        <% end %>
    <% end %>
</div>


app/views/rooms/new.html.erb
<div class="page_sec">
    <h1>Add new room</h1>
    <form action = "<%=create_room_path(@listing.id)%>" method = "POST">
        <input type="hidden" value="<%=form_authenticity_token%>" name="authenticity_token">
        <div>
            <label> Booking Start: </label>
            <input type="date" name="booking[date]">
        </div>
        <div>
            <label> Days: </label>
            <input type="number" min="1" max="100" name="days_num">
        </div>
        <h2>Rooms</h2>
        <div>
            <label>Name: </label>
            <input type="text" name="room[name]">
        </div>
        <div>
            <label>Price: </label>
            <input type="number" name="room[price]">
        </div>
        <div>
            <label>No. people: </label>
            <input type="number" name="room[no_people]">
        </div>
        
        <input type="submit" value="Create">
    </form>
</div>

app/views/rooms/show.html.erb
<div class="page_sec">
    <h3>Room: <%= @room[:name]%></h3>
    <p>Id: <%= @room[:id]%></p>
    <p>$<%= @room[:price]%> - No. people: <%= @room[:no_people]%></p>
    <%= link_to "Edit Room", edit_room_path(@room[:id])%>

    <%= month_calendar events: @bookings do |date, bookings| %>
        <%= date.day %>
        <% bookings.each do |b| %>
            <% if b[:aval] %>
                <p>Vacant</p>
            <% else %>
                <p>No Vacancy</p>
            <% end %>
        <% end %>
    <% end %>
</div>